### ISSUE TITLE
Ads stop loading after `show_rewarded_video` error

### ISSUE THREAD

**Issue by arypbatista** [FrogSquare/GodotFireBase#28]
Sometimes when I show the video I get a null pointer exception. After this error banner and rewarded video ads stop to load.

```
02-19 21:50:33.600: W/Ads(26759): Could not show rewarded video ad from adapter.
02-19 21:50:33.600: W/Ads(26759): java.lang.NullPointerException: Attempt to read from field 'com.google.android.gms.ads.internal.client.bp gx.a' on a null object reference
02-19 21:50:33.600: W/Ads(26759): 	at com.google.ads.mediation.a.h(:com.google.android.gms.DynamiteModulesA@11975436:352)
02-19 21:50:33.600: W/Ads(26759): 	at com.google.android.gms.ads.internal.mediation.client.u.f(:com.google.android.gms.DynamiteModulesA@11975436:194)
02-19 21:50:33.600: W/Ads(26759): 	at com.google.android.gms.ads.internal.reward.b.a(:com.google.android.gms.DynamiteModulesA@11975436:29)
02-19 21:50:33.600: W/Ads(26759): 	at com.google.android.gms.ads.internal.reward.client.e.onTransact(:com.google.android.gms.DynamiteModulesA@11975436:11)
02-19 21:50:33.600: W/Ads(26759): 	at android.os.Binder.transact(Binder.java:387)
02-19 21:50:33.600: W/Ads(26759): 	at com.google.android.gms.internal.zzed.zzb(Unknown Source)
02-19 21:50:33.600: W/Ads(26759): 	at com.google.android.gms.internal.zzacs.show(Unknown Source)
02-19 21:50:33.600: W/Ads(26759): 	at com.google.android.gms.internal.zzadd.show(Unknown Source)
02-19 21:50:33.600: W/Ads(26759): 	at org.godotengine.godot.AdMob.show_rewarded_video(AdMob.java:323)
02-19 21:50:33.600: W/Ads(26759): 	at org.godotengine.godot.FireBase$21.run(FireBase.java:309)
02-19 21:50:33.600: W/Ads(26759): 	at android.os.Handler.handleCallback(Handler.java:746)
02-19 21:50:33.600: W/Ads(26759): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-19 21:50:33.600: W/Ads(26759): 	at android.os.Looper.loop(Looper.java:148)
02-19 21:50:33.600: W/Ads(26759): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
02-19 21:50:33.600: W/Ads(26759): 	at java.lang.reflect.Method.invoke(Native Method)
02-19 21:50:33.600: W/Ads(26759): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
02-19 21:50:33.600: W/Ads(26759): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
02-19 21:50:33.605: W/Ads(26759): Could not call showVideo.
02-19 21:50:33.605: W/Ads(26759): android.os.RemoteException
02-19 21:50:33.605: W/Ads(26759): 	at com.google.android.gms.ads.internal.mediation.client.u.f(:com.google.android.gms.DynamiteModulesA@11975436:198)
02-19 21:50:33.605: W/Ads(26759): 	at com.google.android.gms.ads.internal.reward.b.a(:com.google.android.gms.DynamiteModulesA@11975436:29)
02-19 21:50:33.605: W/Ads(26759): 	at com.google.android.gms.ads.internal.reward.client.e.onTransact(:com.google.android.gms.DynamiteModulesA@11975436:11)
02-19 21:50:33.605: W/Ads(26759): 	at android.os.Binder.transact(Binder.java:387)
02-19 21:50:33.605: W/Ads(26759): 	at com.google.android.gms.internal.zzed.zzb(Unknown Source)
02-19 21:50:33.605: W/Ads(26759): 	at com.google.android.gms.internal.zzacs.show(Unknown Source)
02-19 21:50:33.605: W/Ads(26759): 	at com.google.android.gms.internal.zzadd.show(Unknown Source)
02-19 21:50:33.605: W/Ads(26759): 	at org.godotengine.godot.AdMob.show_rewarded_video(AdMob.java:323)
02-19 21:50:33.605: W/Ads(26759): 	at org.godotengine.godot.FireBase$21.run(FireBase.java:309)
02-19 21:50:33.605: W/Ads(26759): 	at android.os.Handler.handleCallback(Handler.java:746)
02-19 21:50:33.605: W/Ads(26759): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-19 21:50:33.605: W/Ads(26759): 	at android.os.Looper.loop(Looper.java:148)
02-19 21:50:33.605: W/Ads(26759): 	at android.app.ActivityThread.main(ActivityThread.java:5443)
02-19 21:50:33.605: W/Ads(26759): 	at java.lang.reflect.Method.invoke(Native Method)
02-19 21:50:33.605: W/Ads(26759): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
02-19 21:50:33.605: W/Ads(26759): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```

**Comment by arypbatista** [comment]
Seems related to this https://github.com/googleads/googleads-mobile-unity/issues/513

**Comment by arypbatista** [comment]
@RameshRavone I have fixed the issue by removing `reloadRewardedVideo()` from `onRewarded` handler.

I have observed that Rewarded event is triggered immediatly before Close event is triggered. So it ended triggering the reload method twice.

I think it's ok to just reload on fail and on close. I am just wondering if it is ok to reload a video when user closed it but didn't complete it. What do you think?
