### ISSUE TITLE
Latest build breaks with com.google.android.gms:play-services-measurement-base dependency errors

### ISSUE THREAD

**Issue by wombatwingdings** [FrogSquare/GodotFireBase#46]
The latest build seems to be broken. I have done a clean pull and build (Godot 3.1 branch) with this module on two Windows 10 machines. I get the following error:
```
Download https://repo.maven.apache.org/maven2/com/google/auto/value/auto-value-annotations/1.6/auto-value-annotations-1.6.pom
Download https://repo.maven.apache.org/maven2/com/google/auto/value/auto-value-parent/1.6/auto-value-parent-1.6.pom
Download https://repo.maven.apache.org/maven2/com/google/auto/auto-parent/6/auto-parent-6.pom
Download https://repo.maven.apache.org/maven2/com/squareup/okio/okio/1.13.0/okio-1.13.0.pom
Download https://repo.maven.apache.org/maven2/com/squareup/okio/okio-parent/1.13.0/okio-parent-1.13.0.pom
Download https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/16.2.0/play-services-basement-16.2.0.pom

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':checkDebugClasspath' property 'compileClasspath' during up-to-date check.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.3.0,16.3.0], [16.4.0,16.4.0]], but resolves to 16.4.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 42s
1 actionable task: 1 executed
"Finished."
```
Was OK before "Removing depricated Invite" commit. I've looked where else these dependencies are, but I can only find them in this module. Have fiddled with the version numbers in config.py but can't fix it. Any help appreciated.

**Comment by RameshRavone** [comment]
Add this at the end of `platform/android/build.gradle.template`
```
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

**Comment by RameshRavone** [comment]
This is happening because Firebase `core` and `Ads` require different versions of `com.google.android.gms:play-services-measurement-base`,

**Comment by wombatwingdings** [comment]
This does fix the build issue. However, I now get the following crash when trying to use Remote Config. Looking around at similar issues, I believe the duplicate support libraries could be causing this.

```
04-29 20:33:47.474 31220 31220 D AndroidRuntime: Shutting down VM
04-29 20:33:47.476 31220 31220 E AndroidRuntime: FATAL EXCEPTION: main
04-29 20:33:47.476 31220 31220 E AndroidRuntime: Process: com.bunbysoft.rubberrocketracer, PID: 31220
04-29 20:33:47.476 31220 31220 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at com.google.android.gms.common.api.internal.LifecycleActivity.isSupport(Unknown Source:7)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source:2)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source:7)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at com.google.android.gms.tasks.zzu$zza.zza(Unknown Source:1)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at com.google.android.gms.tasks.zzu.addOnCompleteListener(Unknown Source:54)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at org.godotengine.godot.RemoteConfig.fetchRemoteConfigs(RemoteConfig.java:75)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at org.godotengine.godot.RemoteConfig.init(RemoteConfig.java:62)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at org.godotengine.godot.FireBase.initFireBase(FireBase.java:118)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at org.godotengine.godot.FireBase.access$000(FireBase.java:38)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at org.godotengine.godot.FireBase$2.run(FireBase.java:160)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6923)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-29 20:33:47.476 31220 31220 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
04-29 20:33:47.476 31220 31220 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.FragmentActivity" on path: DexPathList[[zip file "/data/app/com.bunbysoft.rubberrocketracer-gNUScno7D4jZRtFwypQo3Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.bunbysoft.rubberrocketracer-gNUScno7D4jZRtFwypQo3Q==/lib/arm, /data/app/com.bunbysoft.rubberrocketracer-
```
Is there a reason why we must stick with the version we are using in config.py?

Thanks for your help and thanks for the great module!

**Comment by wombatwingdings** [comment]
Changing the following dependency in config.py removes the need for disableVersionCheck = true:

from:
```
        env.android_add_dependency(implement("com.google.firebase:firebase-core:16.0.8"))
```
to:
```
        env.android_add_dependency(implement("com.google.firebase:firebase-core:16.0.7"))
```

This will use com.google.android.gms:play-services-measurement-base:16.3.0 (same as what ads requires) and compiles.

I still have the same crash when using Remote Config, so I'm wrong in my previous comment. That must be something else.

Would you be happy using com.google.firebase:firebase-core:16.0.7 in this module?

Thanks.

**Comment by RameshRavone** [comment]
Sure, make a PR, or I'll make it later

**Comment by wombatwingdings** [comment]
Will submit PR. Thanks!

**Comment by wombatwingdings** [comment]
Resolved. Closed.
