### ISSUE TITLE
Unable to Build Export Templates

### ISSUE THREAD

**Issue by ArtimosPenguidor** [FrogSquare/GodotFireBase#55]
Hello,

I've been trying to get this module working on my Godot project for a few days now but I can't manage to get the export templates to build with gradle.

I am using Godot 3.1-stable because I read on a separate issue here that the newer versions of the engine are not compatible yet. I cloned the `GodotFireBase` repo into the `godot/modules` folder and renamed it to `FireBase`. I also cloned the `GodotSQL` repo and renamed it to `SQLBridge`. In the `FireBase` module I set the `p_app_id` to my app and copy my `google-services.json` into the `platforms/android/java` folder. I then run the commands specified in here [https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_android.html#doc-compiling-for-android](https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_android.html#doc-compiling-for-android)

When I run `./gradlew build` I get the following error:

```
./gradlew build --stacktrace

> Configure project : 
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :processDebugGoogleServices 
Parsing json file: /Users/nick/Documents/godot/platform/android/java/google-services.json

> Task :processDebugManifest FAILED
/Users/nick/Documents/godot/platform/android/java/AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:20:5-96:19 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:20:5-96:19 to override.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':processDebugManifest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:20:5-96:19 to override.
        at com.android.builder.core.AndroidBuilder.mergeManifestsForApplication(AndroidBuilder.java:540)
        at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:173)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more


* Get more help at https://help.gradle.org

BUILD FAILED in 0s
13 actionable tasks: 2 executed, 11 up-to-date
```

I have no clue what the problem could be. If it makes any difference, when I run the gradle command, it automatically installed android sdk 28.

Any idea what's going on?

**Comment by omar-bz** [comment]
@ArtimosPenguidor did you solve this issue??

**Comment by ArtimosPenguidor** [comment]
No, unfortunately I am still having the same problem. I have even gotten a new Macbook since I first posted my problem here but the same errors occur.

The steps I took are as follows:

1. Installed SCons java8, android SDK cli tools, android NDK.
2. Downloaded the source for Godot 3.1-stable and built the editor.
3. Built the android template APKs as described [here](https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_android.html) (Which works perfectly fine)
4. Cloned the GodotFireBase module into the `/modules` directory of the godot source.
5. Changed the `p_app_id` in the `config.py` and copied my firebase google-services.json file in the `/platforms/android/java` directory
6. Attempted to rebuild the template APKs.

At this point I am greeted with the error I posted above. I'm not sure if I am using the wrong versions of something but it seems like this `android.support.v4` is conflicting with `androidx` which I have read is the replacement for the former package in newer android versions.

**Comment by omar-bz** [comment]
hey @ArtimosPenguidor i have just compiled the lib by changing the versions of the libraries used,
meanwhile it worth mentioning that i didn't test all the functionalities of the firebase: if there is a compatibility issue between the versions i have used so maybe you will need some extra work to figure out which one is suitable anyway here is a print of the git diff of the lib so you can see the changements i have done( i used gradle 4.10.2 if it is relevent)
![image](https://user-images.githubusercontent.com/20848841/62701849-2a4b4e00-b9dd-11e9-8be0-7c127b9b6d2a.png)

**Comment by ArtimosPenguidor** [comment]
Wow, you are a godsend. I will try these updated dependencies when I get home.

If you don't mind me asking, how did you decide upon these versions of libraries and did you have the same issue as me before changing them?

Thanks again for your suggestion.

**Comment by ArtimosPenguidor** [comment]
Well after bumping those dependencies, and updating my gradle version to 4.10.2 (And installing the GodotSQL package), I was able to successfully build the templates now.

I'm not sure if the packages will run properly once I implement them in my game but it's a great start.

Thanks again for all of your help! I wonder if this issue should be marked for a possible update in this repo.

**Comment by ArtimosPenguidor** [comment]
I may not be completely out of the woods yet. I'm not sure if this is due to the package version changes or I am just doing something dumb.

I got everything to compile and exported my game to an apk. I simply wanted to test the Notification functionality so I added the following code that runs when I open my game.
```
func _ready() -> void:
	if OS.get_name() == "Android":
		firebase.initWithFile("res://godot-firebase-config.json", get_instance_id())
		var dict = {}
		dict["title"] = "WARNING"
		dict["message"] = "This is a test... heh"
		dict["type"] = "text"
		
		firebase.notifyOnComplete(dict, 60)
```

Which returns the following on logcat:
<img width="1361" alt="Screen Shot 2019-08-09 at 8 21 46 PM" src="https://user-images.githubusercontent.com/7527934/62815979-1c352480-bae6-11e9-85e6-025bf3389e4b.png">

So it seems to not fail... but I get no notification. I verify my firebase setup by just sending a test message from the firebase console with the token it generated when running my game and that DOES work.

Am I doing something wrong? or is this a result of changing the dependency versions.
